### ISSUE TITLE
Add Support for primitives in let parameters

### ISSUE THREAD

**Issue by IacobIonut01** [GuilhE/KMP-ComposeUIViewController#1]
https://github.com/GuilhE/KMP-ComposeUIViewController/blob/d77607d5fbab8a525b5e5d74171f73a1f625a563/kmp-composeuiviewcontroller-ksp/src/main/kotlin/com/github/guilhe/kmp/composeuiviewcontroller/ksp/Processor.kt#L127

Add support for primitive types like Int to be used in Callbacks
(```Int -> KotlinInt``` in Representable code)

Without that when adding a parameter like (Int) -> Unit, in Swift it will result the following error
```Cannot convert value of type '(Int) -> Void' to expected argument type '(KotlinInt) -> Void'```

**Comment by GuilhE** [comment]
Thanks for your issue.
Fixed and published to maven, the release is expected to be out soon.

**Comment by IacobIonut01** [comment]
Great!

**Comment by GuilhE** [comment]
It's out https://search.maven.org/artifact/com.github.guilhe.kmp/kmp-composeuiviewcontroller-ksp/1.4.1-ALPHA/jar 🥳
